---
- name: Common setup
  ansible.builtin.import_role:
    name: common
  tags: [always, common]

- name: Python user tools
  ansible.builtin.import_role:
    name: python_user_tools
  tags: [python-user-tools, dotfiles]

- name: Nerd Fonts
  ansible.builtin.import_role:
    name: fonts
  tags: [fonts]

- name: Shell plugins
  ansible.builtin.import_role:
    name: shell_plugins
  tags: [shell]

- name: Apply dotfiles with stown
  ansible.builtin.import_role:
    name: dotfiles
  tags: [dotfiles]
