---
- name: Host Flatpak prerequisites
  tags: [aeon, flatpaks]
  when: not ansible_check_mode
  block:
    - name: Verify flatpak command exists
      ansible.builtin.shell:
        cmd: command -v "{{ item }}"
      loop:
        - bash
        - flatpak
      changed_when: false

- name: Configure Flathub and Flatpaks (user)
  ansible.builtin.import_tasks: flatpaks.yml
  when: not ansible_check_mode
  tags: [aeon, flatpaks]
