ARG BASE_IMAGE=docker.io/library/archlinux:latest
FROM ${BASE_IMAGE}

ARG CONTAINER_USER=dev
ARG CONTAINER_PASSWORD=password

RUN pacman -Syu --noconfirm --needed sudo shadow bash zsh curl git && \
    useradd -m -s /bin/bash ${CONTAINER_USER} && \
    echo "${CONTAINER_USER}:${CONTAINER_PASSWORD}" | chpasswd && \
    usermod -aG wheel ${CONTAINER_USER} && \
    printf '%%wheel ALL=(ALL) ALL\n' > /etc/sudoers.d/99-wheel && \
    chmod 0440 /etc/sudoers.d/99-wheel

WORKDIR /home/${CONTAINER_USER}
