ARG BASE_IMAGE=docker.io/opensuse/tumbleweed:latest
FROM ${BASE_IMAGE}

ARG CONTAINER_USER=dev
ARG CONTAINER_PASSWORD=password

RUN zypper --non-interactive install --no-recommends sudo shadow bash zsh curl git && \
    useradd -m -s /bin/bash ${CONTAINER_USER} && \
    echo "${CONTAINER_USER}:${CONTAINER_PASSWORD}" | chpasswd && \
    printf 'Defaults:%s !targetpw\n%s ALL=(ALL) ALL\n' "${CONTAINER_USER}" "${CONTAINER_USER}" > /etc/sudoers.d/99-${CONTAINER_USER} && \
    chmod 0440 /etc/sudoers.d/99-${CONTAINER_USER} && \
    zypper clean --all

WORKDIR /home/${CONTAINER_USER}
